<?php

return [
    'emi-calculator' => [
        'slug' => 'emi-calculator',
        'title' => 'EMI Calculator',
        'h1' => 'EMI Calculator',
        'category' => 'loan-calculators',
        'type' => 'amortized_loan',
        'featured' => true,
        'popular' => true,
        'short_description' => 'Estimate monthly equated installments, total interest, and total repayment for any fixed-rate loan.',
        'meta_title' => 'EMI Calculator: Monthly Payment, Interest & Total Repayment',
        'meta_description' => 'Use our EMI calculator to estimate monthly installments, total interest, and total repayment for fixed-rate borrowing scenarios worldwide.',
        'intro' => 'Use this EMI calculator to estimate a predictable monthly installment for loans with a fixed interest rate. It works well for personal finance planning, lending comparisons, and affordability checks.',
        'formula' => 'EMI = P × r × (1 + r)^n ÷ ((1 + r)^n - 1), where P is principal, r is monthly interest rate, and n is total monthly payments.',
        'benefits' => [
            'Compare borrowing scenarios before applying for a loan.',
            'Understand how tenure changes monthly cash flow and lifetime interest.',
            'Use the results as a quick affordability benchmark.',
        ],
        'fields' => [
            'principal' => ['label' => 'Loan amount', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 250000, 'rules' => ['required', 'numeric', 'gt:0']],
            'rate' => ['label' => 'Annual interest rate (%)', 'type' => 'number', 'step' => '0.01', 'default' => 7.25, 'rules' => ['required', 'numeric', 'min:0']],
            'tenure' => ['label' => 'Loan term', 'type' => 'number', 'step' => '1', 'default' => 20, 'rules' => ['required', 'numeric', 'gt:0']],
            'tenure_type' => ['label' => 'Term unit', 'type' => 'select', 'default' => 'years', 'options' => ['years' => 'Years', 'months' => 'Months'], 'rules' => ['required', 'in:years,months']],
        ],
        'faqs' => [
            ['question' => 'What is an EMI?', 'answer' => 'EMI stands for equated monthly installment. It is the fixed monthly payment used to repay a loan over a chosen term at a stated rate.'],
            ['question' => 'Does a longer loan term lower my EMI?', 'answer' => 'Usually yes. A longer term spreads repayment across more months, which reduces the monthly amount but often increases total interest.'],
        ],
        'related' => ['loan-calculator', 'mortgage-calculator', 'loan-eligibility-calculator'],
    ],
    'loan-calculator' => [
        'slug' => 'loan-calculator',
        'title' => 'Loan Calculator',
        'h1' => 'Loan Calculator',
        'category' => 'loan-calculators',
        'type' => 'amortized_loan',
        'featured' => true,
        'popular' => true,
        'short_description' => 'Estimate monthly loan payments, total interest, and full repayment cost.',
        'meta_title' => 'Loan Calculator: Payment, Interest & Total Cost',
        'meta_description' => 'Estimate monthly loan payments, total interest, and full repayment cost with a fast global loan calculator.',
        'intro' => 'This general loan calculator helps you estimate fixed monthly payments for many types of installment borrowing.',
        'formula' => 'Monthly payment uses the standard amortization formula for fixed-rate installment loans.',
        'benefits' => ['Model personal, education, or business borrowing.', 'Compare rates and loan terms side by side.', 'Spot the long-term cost of borrowing.'],
        'fields' => [
            'principal' => ['label' => 'Loan amount', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 50000, 'rules' => ['required', 'numeric', 'gt:0']],
            'rate' => ['label' => 'Annual interest rate (%)', 'type' => 'number', 'step' => '0.01', 'default' => 8.5, 'rules' => ['required', 'numeric', 'min:0']],
            'tenure' => ['label' => 'Loan term', 'type' => 'number', 'step' => '1', 'default' => 5, 'rules' => ['required', 'numeric', 'gt:0']],
            'tenure_type' => ['label' => 'Term unit', 'type' => 'select', 'default' => 'years', 'options' => ['years' => 'Years', 'months' => 'Months'], 'rules' => ['required', 'in:years,months']],
        ],
        'faqs' => [
            ['question' => 'How is total interest calculated?', 'answer' => 'Total interest is the full amount repaid minus the original principal.'],
            ['question' => 'Can this calculator be used for any currency?', 'answer' => 'Yes. The math is currency-agnostic as long as your inputs and interpretation use the same currency.'],
        ],
        'related' => ['emi-calculator', 'personal-loan-calculator', 'car-loan-calculator'],
    ],
    'mortgage-calculator' => [
        'slug' => 'mortgage-calculator',
        'title' => 'Mortgage Calculator',
        'h1' => 'Mortgage Calculator',
        'category' => 'loan-calculators',
        'type' => 'mortgage',
        'featured' => true,
        'popular' => true,
        'short_description' => 'Estimate monthly mortgage payments, total interest, and lifetime repayment for a home purchase.',
        'meta_title' => 'Mortgage Calculator: Monthly Payment & Total Interest',
        'meta_description' => 'Estimate your mortgage payment, borrowing amount, total interest, and total repayment for a home purchase.',
        'intro' => 'Plan your property financing by estimating the financed amount after down payment and the monthly mortgage payment over the chosen term.',
        'formula' => 'Financed amount = property price - down payment. Monthly payment then follows the standard amortization formula.',
        'benefits' => ['Understand how down payment changes affordability.', 'Project lifetime financing cost before speaking with lenders.', 'Model different rates and terms quickly.'],
        'fields' => [
            'home_price' => ['label' => 'Home price', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 450000, 'rules' => ['required', 'numeric', 'gt:0']],
            'down_payment' => ['label' => 'Down payment', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 90000, 'rules' => ['required', 'numeric', 'min:0']],
            'rate' => ['label' => 'Annual interest rate (%)', 'type' => 'number', 'step' => '0.01', 'default' => 6.4, 'rules' => ['required', 'numeric', 'min:0']],
            'loan_term_years' => ['label' => 'Loan term (years)', 'type' => 'number', 'step' => '1', 'default' => 30, 'rules' => ['required', 'numeric', 'gt:0']],
        ],
        'faqs' => [
            ['question' => 'Does this include taxes or insurance?', 'answer' => 'No. This starter mortgage calculator focuses on principal and interest so the result stays clear and globally reusable.'],
            ['question' => 'What if my down payment is zero?', 'answer' => 'The calculator can still estimate the payment, but many lenders apply additional conditions in real-world scenarios.'],
        ],
        'related' => ['home-loan-calculator', 'emi-calculator', 'loan-calculator'],
    ],
    'home-loan-calculator' => [
        'slug' => 'home-loan-calculator',
        'title' => 'Home Loan Calculator',
        'h1' => 'Home Loan Calculator',
        'category' => 'loan-calculators',
        'type' => 'mortgage',
        'indexable' => false,
        'short_description' => 'Estimate monthly home loan repayments and total interest.',
        'meta_title' => 'Home Loan Calculator: Monthly Payment Estimate',
        'meta_description' => 'Estimate monthly home loan payments, borrowing amount, and total interest with a fast home loan calculator.',
        'intro' => 'Use the home loan calculator to estimate financing costs for residential property purchases.',
        'formula' => 'The tool calculates the financed amount after down payment and applies fixed-rate amortization over the selected term.',
        'benefits' => ['Plan home ownership more confidently.', 'Compare down payment scenarios.', 'Estimate long-term interest cost.'],
        'fields' => [
            'home_price' => ['label' => 'Property price', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 350000, 'rules' => ['required', 'numeric', 'gt:0']],
            'down_payment' => ['label' => 'Down payment', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 70000, 'rules' => ['required', 'numeric', 'min:0']],
            'rate' => ['label' => 'Annual interest rate (%)', 'type' => 'number', 'step' => '0.01', 'default' => 6.1, 'rules' => ['required', 'numeric', 'min:0']],
            'loan_term_years' => ['label' => 'Loan term (years)', 'type' => 'number', 'step' => '1', 'default' => 25, 'rules' => ['required', 'numeric', 'gt:0']],
        ],
        'faqs' => [
            ['question' => 'Is a home loan the same as a mortgage?', 'answer' => 'In many markets the terms are used similarly, but local legal structures can differ. This calculator covers the core repayment math.'],
            ['question' => 'Can I compare different terms?', 'answer' => 'Yes. Try multiple loan term values to compare monthly affordability against total interest cost.'],
        ],
        'related' => ['mortgage-calculator', 'emi-calculator', 'loan-eligibility-calculator'],
    ],
    'car-loan-calculator' => [
        'slug' => 'car-loan-calculator',
        'title' => 'Car Loan Calculator',
        'h1' => 'Car Loan Calculator',
        'category' => 'loan-calculators',
        'type' => 'amortized_loan',
        'short_description' => 'Estimate auto loan payments, total interest, and repayment cost.',
        'meta_title' => 'Car Loan Calculator: Auto Payment Estimate',
        'meta_description' => 'Estimate car loan payments, interest, and full repayment cost with a clean auto finance calculator.',
        'intro' => 'Model car financing with a simple monthly payment and total cost estimate.',
        'formula' => 'Monthly payment follows the standard fixed-rate amortization formula.',
        'benefits' => ['Compare monthly affordability across loan terms.', 'Estimate interest before visiting a dealership.', 'Keep transport financing aligned with your budget.'],
        'fields' => [
            'principal' => ['label' => 'Vehicle loan amount', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 28000, 'rules' => ['required', 'numeric', 'gt:0']],
            'rate' => ['label' => 'Annual interest rate (%)', 'type' => 'number', 'step' => '0.01', 'default' => 6.9, 'rules' => ['required', 'numeric', 'min:0']],
            'tenure' => ['label' => 'Loan term', 'type' => 'number', 'step' => '1', 'default' => 5, 'rules' => ['required', 'numeric', 'gt:0']],
            'tenure_type' => ['label' => 'Term unit', 'type' => 'select', 'default' => 'years', 'options' => ['years' => 'Years', 'months' => 'Months'], 'rules' => ['required', 'in:years,months']],
        ],
        'faqs' => [
            ['question' => 'Can this calculator include a trade-in?', 'answer' => 'Not yet. You can subtract any trade-in value from the amount financed before entering the loan amount.'],
            ['question' => 'Why does a shorter term cost less overall?', 'answer' => 'You repay the balance faster, so less interest has time to accrue.'],
        ],
        'related' => ['loan-calculator', 'personal-loan-calculator', 'budget-calculator'],
    ],
    'personal-loan-calculator' => [
        'slug' => 'personal-loan-calculator',
        'title' => 'Personal Loan Calculator',
        'h1' => 'Personal Loan Calculator',
        'category' => 'loan-calculators',
        'type' => 'amortized_loan',
        'indexable' => false,
        'short_description' => 'Estimate personal loan EMIs, total interest, and total repayment.',
        'meta_title' => 'Personal Loan Calculator: Monthly Payment Estimate',
        'meta_description' => 'Use our personal loan calculator to estimate monthly payments, interest, and total repayment.',
        'intro' => 'Estimate repayment plans for unsecured borrowing and compare rates before applying.',
        'formula' => 'Payments are estimated using the standard amortized loan formula.',
        'benefits' => ['Understand your likely monthly commitment.', 'Test multiple loan terms.', 'Visualize the cost of higher interest rates.'],
        'fields' => [
            'principal' => ['label' => 'Loan amount', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 18000, 'rules' => ['required', 'numeric', 'gt:0']],
            'rate' => ['label' => 'Annual interest rate (%)', 'type' => 'number', 'step' => '0.01', 'default' => 11.5, 'rules' => ['required', 'numeric', 'min:0']],
            'tenure' => ['label' => 'Loan term', 'type' => 'number', 'step' => '1', 'default' => 4, 'rules' => ['required', 'numeric', 'gt:0']],
            'tenure_type' => ['label' => 'Term unit', 'type' => 'select', 'default' => 'years', 'options' => ['years' => 'Years', 'months' => 'Months'], 'rules' => ['required', 'in:years,months']],
        ],
        'faqs' => [
            ['question' => 'Is the payment fixed?', 'answer' => 'The estimate assumes a fixed interest rate and equal installments over the full term.'],
            ['question' => 'Can fees be included?', 'answer' => 'Not directly in this version, but you can add fees to the loan amount if you want a rough blended estimate.'],
        ],
        'related' => ['loan-calculator', 'emi-calculator', 'debt-payoff-calculator'],
    ],
    'student-loan-calculator' => [
        'slug' => 'student-loan-calculator',
        'title' => 'Student Loan Calculator',
        'h1' => 'Student Loan Calculator',
        'category' => 'loan-calculators',
        'type' => 'amortized_loan',
        'indexable' => false,
        'short_description' => 'Estimate student loan monthly payments and lifetime interest.',
        'meta_title' => 'Student Loan Calculator: Repayment Estimate',
        'meta_description' => 'Estimate student loan payments, total interest, and repayment costs with a simple education loan calculator.',
        'intro' => 'This calculator helps estimate repayment for education borrowing using a fixed-rate installment model.',
        'formula' => 'The repayment estimate follows standard fixed-rate amortization math.',
        'benefits' => ['Compare education financing options.', 'Understand the long-term cost of borrowing.', 'Use longer and shorter terms to explore repayment flexibility.'],
        'fields' => [
            'principal' => ['label' => 'Loan amount', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 42000, 'rules' => ['required', 'numeric', 'gt:0']],
            'rate' => ['label' => 'Annual interest rate (%)', 'type' => 'number', 'step' => '0.01', 'default' => 5.8, 'rules' => ['required', 'numeric', 'min:0']],
            'tenure' => ['label' => 'Repayment term', 'type' => 'number', 'step' => '1', 'default' => 10, 'rules' => ['required', 'numeric', 'gt:0']],
            'tenure_type' => ['label' => 'Term unit', 'type' => 'select', 'default' => 'years', 'options' => ['years' => 'Years', 'months' => 'Months'], 'rules' => ['required', 'in:years,months']],
        ],
        'faqs' => [
            ['question' => 'Does this include grace periods?', 'answer' => 'No. This version assumes repayment starts immediately under a standard fixed schedule.'],
            ['question' => 'Why use this before borrowing?', 'answer' => 'It helps you estimate future repayment pressure and compare multiple borrowing plans.'],
        ],
        'related' => ['loan-calculator', 'debt-payoff-calculator', 'salary-calculator'],
    ],
    'sip-calculator' => [
        'slug' => 'sip-calculator',
        'title' => 'SIP Calculator',
        'h1' => 'SIP Calculator',
        'category' => 'investment-calculators',
        'type' => 'sip',
        'featured' => true,
        'popular' => true,
        'short_description' => 'Project the maturity value of recurring monthly investments and estimated returns.',
        'meta_title' => 'SIP Calculator: Monthly Investment Growth Projection',
        'meta_description' => 'Estimate future value, total invested amount, and returns from recurring monthly investments with our SIP calculator.',
        'intro' => 'Project how consistent monthly investing can compound over time using an expected annual return.',
        'formula' => 'Future value is calculated as a series of monthly contributions compounded at the expected monthly return rate.',
        'benefits' => ['See the long-term power of recurring investing.', 'Compare different monthly contribution levels.', 'Visualize estimated gain versus total invested amount.'],
        'fields' => [
            'monthly_investment' => ['label' => 'Monthly investment', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 500, 'rules' => ['required', 'numeric', 'gt:0']],
            'rate' => ['label' => 'Expected annual return (%)', 'type' => 'number', 'step' => '0.01', 'default' => 10, 'rules' => ['required', 'numeric', 'min:0']],
            'years' => ['label' => 'Investment period (years)', 'type' => 'number', 'step' => '1', 'default' => 15, 'rules' => ['required', 'numeric', 'gt:0']],
        ],
        'faqs' => [
            ['question' => 'Is the return guaranteed?', 'answer' => 'No. The result is an estimate based on the expected return you enter. Actual market outcomes can differ.'],
            ['question' => 'What does invested amount mean?', 'answer' => 'It is the sum of all monthly contributions you make during the selected period.'],
        ],
        'related' => ['investment-calculator', 'compound-interest-calculator', 'retirement-calculator'],
    ],
    'compound-interest-calculator' => [
        'slug' => 'compound-interest-calculator',
        'title' => 'Compound Interest Calculator',
        'h1' => 'Compound Interest Calculator',
        'category' => 'investment-calculators',
        'type' => 'compound_interest',
        'featured' => true,
        'popular' => true,
        'short_description' => 'Estimate compound growth for a lump-sum amount over time.',
        'meta_title' => 'Compound Interest Calculator: Final Amount & Interest Earned',
        'meta_description' => 'Estimate the future value of a lump-sum investment with compounding using our compound interest calculator.',
        'intro' => 'Use this calculator to project how a lump-sum amount may grow over time with compounding.',
        'formula' => 'A = P × (1 + r / n)^(n × t), where P is principal, r is annual rate, n is compounding periods per year, and t is time in years.',
        'benefits' => ['Visualize how time affects growth.', 'Compare monthly, quarterly, and annual compounding.', 'Estimate interest earned on a starting balance.'],
        'fields' => [
            'principal' => ['label' => 'Initial amount', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 10000, 'rules' => ['required', 'numeric', 'gt:0']],
            'rate' => ['label' => 'Annual interest rate (%)', 'type' => 'number', 'step' => '0.01', 'default' => 8, 'rules' => ['required', 'numeric', 'min:0']],
            'frequency' => ['label' => 'Compounding frequency', 'type' => 'select', 'default' => '12', 'options' => ['1' => 'Annually', '4' => 'Quarterly', '12' => 'Monthly', '365' => 'Daily'], 'rules' => ['required', 'in:1,4,12,365']],
            'years' => ['label' => 'Time period (years)', 'type' => 'number', 'step' => '1', 'default' => 10, 'rules' => ['required', 'numeric', 'gt:0']],
        ],
        'faqs' => [
            ['question' => 'What is compound interest?', 'answer' => 'Compound interest means interest is earned on both the original amount and the accumulated interest from prior periods.'],
            ['question' => 'Why does compounding frequency matter?', 'answer' => 'More frequent compounding can slightly increase the final amount when the rate and time period stay the same.'],
        ],
        'related' => ['investment-calculator', 'savings-calculator', 'sip-calculator'],
    ],
    'investment-calculator' => [
        'slug' => 'investment-calculator',
        'title' => 'Investment Calculator',
        'h1' => 'Investment Calculator',
        'category' => 'investment-calculators',
        'type' => 'investment',
        'featured' => true,
        'short_description' => 'Estimate future value for an initial investment plus ongoing monthly contributions.',
        'meta_title' => 'Investment Calculator: Future Value Projection',
        'meta_description' => 'Estimate future investment value with both an initial deposit and ongoing monthly contributions.',
        'intro' => 'Model long-term investing with both a starting amount and monthly additions.',
        'formula' => 'The result combines compound growth on the initial amount plus compounded monthly contributions over the investment horizon.',
        'benefits' => ['See how an early lump sum accelerates growth.', 'Test higher or lower monthly contributions.', 'Compare realistic long-term scenarios.'],
        'fields' => [
            'initial_investment' => ['label' => 'Initial investment', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 25000, 'rules' => ['required', 'numeric', 'min:0']],
            'monthly_contribution' => ['label' => 'Monthly contribution', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 750, 'rules' => ['required', 'numeric', 'min:0']],
            'rate' => ['label' => 'Expected annual return (%)', 'type' => 'number', 'step' => '0.01', 'default' => 9, 'rules' => ['required', 'numeric', 'min:0']],
            'years' => ['label' => 'Investment period (years)', 'type' => 'number', 'step' => '1', 'default' => 20, 'rules' => ['required', 'numeric', 'gt:0']],
        ],
        'faqs' => [
            ['question' => 'Can I use zero as the initial investment?', 'answer' => 'Yes. The calculator still works and becomes a monthly contribution projection.'],
            ['question' => 'Are inflation and fees included?', 'answer' => 'No. This version focuses on nominal growth using the return you enter.'],
        ],
        'related' => ['sip-calculator', 'compound-interest-calculator', 'retirement-calculator'],
    ],
    'savings-calculator' => [
        'slug' => 'savings-calculator',
        'title' => 'Savings Calculator',
        'h1' => 'Savings Calculator',
        'category' => 'investment-calculators',
        'type' => 'investment',
        'indexable' => false,
        'short_description' => 'Estimate the future value of your savings plan with optional starting balance and recurring deposits.',
        'meta_title' => 'Savings Calculator: Future Savings Projection',
        'meta_description' => 'Estimate future savings growth with monthly deposits, a starting balance, and an expected interest rate.',
        'intro' => 'Project how a disciplined savings plan can grow over time using recurring monthly deposits.',
        'formula' => 'Savings growth combines compounding on the opening balance plus recurring monthly deposits.',
        'benefits' => ['Set realistic savings targets.', 'Compare scenarios with and without a starting balance.', 'Understand estimated interest earned over time.'],
        'fields' => [
            'initial_investment' => ['label' => 'Starting balance', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 5000, 'rules' => ['required', 'numeric', 'min:0']],
            'monthly_contribution' => ['label' => 'Monthly savings', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 400, 'rules' => ['required', 'numeric', 'min:0']],
            'rate' => ['label' => 'Annual interest rate (%)', 'type' => 'number', 'step' => '0.01', 'default' => 4.5, 'rules' => ['required', 'numeric', 'min:0']],
            'years' => ['label' => 'Savings period (years)', 'type' => 'number', 'step' => '1', 'default' => 8, 'rules' => ['required', 'numeric', 'gt:0']],
        ],
        'faqs' => [
            ['question' => 'Is this only for bank savings?', 'answer' => 'No. It works for any recurring savings plan using the interest or return rate you choose.'],
            ['question' => 'Can the monthly amount be zero?', 'answer' => 'Yes. In that case the result reflects growth on the starting balance only.'],
        ],
        'related' => ['compound-interest-calculator', 'fd-calculator', 'rd-calculator'],
    ],
    'retirement-calculator' => [
        'slug' => 'retirement-calculator',
        'title' => 'Retirement Calculator',
        'h1' => 'Retirement Calculator',
        'category' => 'investment-calculators',
        'type' => 'retirement',
        'featured' => true,
        'short_description' => 'Project a retirement corpus using age, monthly savings, and expected return.',
        'meta_title' => 'Retirement Calculator: Future Retirement Corpus Projection',
        'meta_description' => 'Estimate your projected retirement corpus using your current age, retirement age, monthly savings, and expected return.',
        'intro' => 'Estimate how much your retirement savings could grow to by the time you stop working.',
        'formula' => 'The calculator compounds current retirement savings and ongoing monthly contributions until the selected retirement age.',
        'benefits' => ['Set a clearer retirement savings target.', 'Test the impact of saving more each month.', 'Understand the long-term effect of time in the market.'],
        'fields' => [
            'current_age' => ['label' => 'Current age', 'type' => 'number', 'step' => '1', 'default' => 32, 'rules' => ['required', 'integer', 'min:18', 'max:80']],
            'retirement_age' => ['label' => 'Retirement age', 'type' => 'number', 'step' => '1', 'default' => 65, 'rules' => ['required', 'integer', 'min:19', 'max:90']],
            'monthly_savings' => ['label' => 'Monthly savings', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 900, 'rules' => ['required', 'numeric', 'min:0']],
            'current_savings' => ['label' => 'Current retirement savings', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 30000, 'rules' => ['required', 'numeric', 'min:0']],
            'rate' => ['label' => 'Expected annual return (%)', 'type' => 'number', 'step' => '0.01', 'default' => 7.5, 'rules' => ['required', 'numeric', 'min:0']],
        ],
        'faqs' => [
            ['question' => 'What if I already have some retirement savings?', 'answer' => 'Enter them as current retirement savings so the projection includes both your current balance and future contributions.'],
            ['question' => 'Should I use a real return after inflation?', 'answer' => 'That can be a helpful planning approach. You can reduce the expected return to create a more conservative estimate.'],
        ],
        'related' => ['sip-calculator', 'investment-calculator', 'savings-calculator'],
    ],
    'fd-calculator' => [
        'slug' => 'fd-calculator',
        'title' => 'FD Calculator',
        'h1' => 'FD Calculator',
        'category' => 'investment-calculators',
        'type' => 'fixed_deposit',
        'indexable' => false,
        'short_description' => 'Estimate maturity value and interest earned on a fixed deposit.',
        'meta_title' => 'FD Calculator: Fixed Deposit Maturity Estimate',
        'meta_description' => 'Estimate fixed deposit maturity value and interest earned over time with compounding.',
        'intro' => 'Project maturity value for a fixed deposit using deposit amount, annual rate, and tenure.',
        'formula' => 'A fixed deposit estimate applies compound growth to a one-time deposit over the selected term.',
        'benefits' => ['Estimate maturity value before locking funds.', 'Compare rate scenarios.', 'Understand total interest earned.'],
        'fields' => [
            'principal' => ['label' => 'Deposit amount', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 15000, 'rules' => ['required', 'numeric', 'gt:0']],
            'rate' => ['label' => 'Annual interest rate (%)', 'type' => 'number', 'step' => '0.01', 'default' => 5.5, 'rules' => ['required', 'numeric', 'min:0']],
            'years' => ['label' => 'Tenure (years)', 'type' => 'number', 'step' => '1', 'default' => 3, 'rules' => ['required', 'numeric', 'gt:0']],
        ],
        'faqs' => [
            ['question' => 'Does this assume reinvested interest?', 'answer' => 'Yes. The estimate uses compounding, which assumes interest remains in the deposit.'],
            ['question' => 'Can I use this for time deposits worldwide?', 'answer' => 'Yes. The underlying math applies broadly to fixed deposit style products.'],
        ],
        'related' => ['rd-calculator', 'savings-calculator', 'compound-interest-calculator'],
    ],
    'rd-calculator' => [
        'slug' => 'rd-calculator',
        'title' => 'RD Calculator',
        'h1' => 'RD Calculator',
        'category' => 'investment-calculators',
        'type' => 'recurring_deposit',
        'indexable' => false,
        'short_description' => 'Estimate maturity value for recurring monthly deposits over time.',
        'meta_title' => 'RD Calculator: Recurring Deposit Maturity Estimate',
        'meta_description' => 'Estimate recurring deposit maturity value, total deposits, and interest earned over time.',
        'intro' => 'Use this recurring deposit calculator to estimate maturity value when you deposit a fixed amount every month.',
        'formula' => 'The result compounds monthly deposits across the selected tenure using the annual interest rate you enter.',
        'benefits' => ['See how monthly savings accumulate.', 'Estimate maturity for recurring deposit style products.', 'Compare alternative monthly deposit levels.'],
        'fields' => [
            'monthly_investment' => ['label' => 'Monthly deposit', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 300, 'rules' => ['required', 'numeric', 'gt:0']],
            'rate' => ['label' => 'Annual interest rate (%)', 'type' => 'number', 'step' => '0.01', 'default' => 5.2, 'rules' => ['required', 'numeric', 'min:0']],
            'years' => ['label' => 'Tenure (years)', 'type' => 'number', 'step' => '1', 'default' => 4, 'rules' => ['required', 'numeric', 'gt:0']],
        ],
        'faqs' => [
            ['question' => 'How is RD different from FD?', 'answer' => 'A recurring deposit uses regular monthly contributions, while a fixed deposit usually starts with one lump sum.'],
            ['question' => 'Can I use a custom currency?', 'answer' => 'Yes. The calculator works for any currency as long as you use the same unit throughout.'],
        ],
        'related' => ['fd-calculator', 'sip-calculator', 'savings-calculator'],
    ],
    'income-tax-calculator' => [
        'slug' => 'income-tax-calculator',
        'title' => 'Income Tax Calculator',
        'h1' => 'Income Tax Calculator',
        'category' => 'tax-calculators',
        'type' => 'income_tax',
        'featured' => true,
        'short_description' => 'Estimate annual income tax using a generic progressive model with deductions.',
        'meta_title' => 'Income Tax Calculator: Estimated Annual Tax & Net Income',
        'meta_description' => 'Estimate annual income tax, effective tax rate, and net income using a flexible income tax calculator.',
        'intro' => 'This income tax calculator uses a simplified progressive structure to give a practical estimate for common planning scenarios.',
        'formula' => 'Taxable income = annual income - deductions. Tax is then estimated across progressive brackets selected in the model.',
        'benefits' => ['Estimate annual tax in a transparent way.', 'See how deductions affect taxable income.', 'Use a clear starting point before checking official local rules.'],
        'fields' => [
            'annual_income' => ['label' => 'Annual income', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 85000, 'rules' => ['required', 'numeric', 'gt:0']],
            'deductions' => ['label' => 'Annual deductions', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 5000, 'rules' => ['required', 'numeric', 'min:0']],
            'country' => ['label' => 'Country / tax model', 'type' => 'select', 'default' => 'us', 'options' => ['us' => 'United States', 'uk' => 'United Kingdom', 'in' => 'India', 'generic' => 'Generic international'], 'rules' => ['required', 'in:us,uk,in,generic']],
            'filing_status' => ['label' => 'Filing status', 'type' => 'select', 'default' => 'single', 'options' => ['single' => 'Single', 'joint' => 'Joint / household'], 'rules' => ['required', 'in:single,joint']],
        ],
        'faqs' => [
            ['question' => 'Is this a country-specific tax calculator?', 'answer' => 'Not yet. This version uses a simplified progressive model intended as a broadly understandable estimate.'],
            ['question' => 'Should I still check official local rules?', 'answer' => 'Yes. This tool is best used for planning, while final tax decisions should be checked against current local rules or professional advice.'],
        ],
        'related' => ['salary-calculator', 'take-home-salary-calculator', 'gst-calculator'],
    ],
    'salary-calculator' => [
        'slug' => 'salary-calculator',
        'title' => 'Salary Calculator',
        'h1' => 'Salary Calculator',
        'category' => 'salary-calculators',
        'type' => 'salary',
        'short_description' => 'Convert hourly work assumptions into annual, monthly, weekly, and daily gross salary estimates.',
        'meta_title' => 'Salary Calculator: Gross Pay by Hour, Week, Month & Year',
        'meta_description' => 'Estimate salary from hourly rate, hours worked, and working weeks with a clean salary calculator.',
        'intro' => 'Translate hourly work assumptions into yearly, monthly, weekly, and daily pay estimates.',
        'formula' => 'Annual salary = hourly rate × hours per week × weeks worked per year.',
        'benefits' => ['Compare freelance, hourly, and salaried scenarios.', 'Convert work assumptions into annual planning numbers.', 'Use the outputs for budgeting and take-home estimates.'],
        'fields' => [
            'hourly_rate' => ['label' => 'Hourly rate', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 35, 'rules' => ['required', 'numeric', 'gt:0']],
            'hours_per_week' => ['label' => 'Hours per week', 'type' => 'number', 'step' => '0.1', 'default' => 40, 'rules' => ['required', 'numeric', 'gt:0']],
            'weeks_per_year' => ['label' => 'Weeks worked per year', 'type' => 'number', 'step' => '1', 'default' => 50, 'rules' => ['required', 'numeric', 'gt:0', 'max:52']],
        ],
        'faqs' => [
            ['question' => 'Does this include bonuses?', 'answer' => 'No. This version focuses on base gross pay derived from hourly work assumptions.'],
            ['question' => 'Can I use it for part-time work?', 'answer' => 'Yes. Enter your expected hours per week and weeks worked per year.'],
        ],
        'related' => ['take-home-salary-calculator', 'hourly-wage-calculator', 'budget-calculator'],
    ],
    'take-home-salary-calculator' => [
        'slug' => 'take-home-salary-calculator',
        'title' => 'Take Home Salary Calculator',
        'h1' => 'Take Home Salary Calculator',
        'category' => 'salary-calculators',
        'type' => 'take_home_salary',
        'featured' => true,
        'short_description' => 'Estimate net pay after tax, pension, and additional deductions.',
        'meta_title' => 'Take Home Salary Calculator: Net Monthly & Annual Pay',
        'meta_description' => 'Estimate take-home salary after taxes, pension, and other deductions with a globally flexible net pay calculator.',
        'intro' => 'Estimate what remains from gross salary after tax and deduction assumptions.',
        'formula' => 'Net pay = gross income - taxes - pension contributions - other deductions.',
        'benefits' => ['Estimate spending power instead of gross salary alone.', 'Compare how deduction rates affect net income.', 'Turn salary figures into more practical monthly planning numbers.'],
        'fields' => [
            'annual_salary' => ['label' => 'Gross annual salary', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 72000, 'rules' => ['required', 'numeric', 'gt:0']],
            'country' => ['label' => 'Country / payroll model', 'type' => 'select', 'default' => 'us', 'options' => ['us' => 'United States', 'uk' => 'United Kingdom', 'in' => 'India', 'generic' => 'Generic international'], 'rules' => ['required', 'in:us,uk,in,generic']],
            'filing_status' => ['label' => 'Filing status', 'type' => 'select', 'default' => 'single', 'options' => ['single' => 'Single', 'joint' => 'Joint / household'], 'rules' => ['required', 'in:single,joint']],
            'other_deductions' => ['label' => 'Other annual deductions', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 1200, 'rules' => ['required', 'numeric', 'min:0']],
        ],
        'faqs' => [
            ['question' => 'Why is this an estimate rather than an exact payroll figure?', 'answer' => 'Payroll rules, deductions, and employer setups vary, so this calculator is designed as a practical estimate rather than an official payslip replacement.'],
            ['question' => 'Why use tax rate instead of local brackets here?', 'answer' => 'It keeps the first version globally usable while still providing a practical take-home estimate.'],
        ],
        'related' => ['salary-calculator', 'income-tax-calculator', 'budget-calculator'],
    ],
    'hourly-wage-calculator' => [
        'slug' => 'hourly-wage-calculator',
        'title' => 'Hourly Wage Calculator',
        'h1' => 'Hourly Wage Calculator',
        'category' => 'salary-calculators',
        'type' => 'hourly_wage',
        'indexable' => false,
        'short_description' => 'Convert annual salary into hourly, weekly, and monthly pay estimates.',
        'meta_title' => 'Hourly Wage Calculator: Convert Salary to Hourly Rate',
        'meta_description' => 'Convert annual salary to estimated hourly wage using your weekly hours and working weeks.',
        'intro' => 'Convert annual gross income into an estimated hourly rate based on working time assumptions.',
        'formula' => 'Hourly wage = annual salary ÷ (hours per week × weeks worked per year).',
        'benefits' => ['Benchmark job offers more clearly.', 'Compare salaried and hourly roles.', 'Translate annual compensation into working-time value.'],
        'fields' => [
            'annual_salary' => ['label' => 'Annual salary', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 64000, 'rules' => ['required', 'numeric', 'gt:0']],
            'hours_per_week' => ['label' => 'Hours per week', 'type' => 'number', 'step' => '0.1', 'default' => 40, 'rules' => ['required', 'numeric', 'gt:0']],
            'weeks_per_year' => ['label' => 'Weeks worked per year', 'type' => 'number', 'step' => '1', 'default' => 50, 'rules' => ['required', 'numeric', 'gt:0', 'max:52']],
        ],
        'faqs' => [
            ['question' => 'Does this include overtime?', 'answer' => 'No. The calculation assumes a steady average schedule across the year.'],
            ['question' => 'Why do weeks worked matter?', 'answer' => 'Fewer weeks worked spread the same annual salary over less time, which increases the implied hourly rate.'],
        ],
        'related' => ['salary-calculator', 'take-home-salary-calculator', 'expense-calculator'],
    ],
    'gst-calculator' => [
        'slug' => 'gst-calculator',
        'title' => 'GST Calculator',
        'h1' => 'GST Calculator',
        'category' => 'tax-calculators',
        'type' => 'sales_tax',
        'short_description' => 'Add or remove GST from an amount using inclusive or exclusive pricing.',
        'meta_title' => 'GST Calculator: Add or Remove Tax from an Amount',
        'meta_description' => 'Calculate GST amount, gross total, and pre-tax value with inclusive or exclusive pricing modes.',
        'intro' => 'Use this tax calculator to add or extract GST from an amount in a clear, globally understandable way.',
        'formula' => 'Exclusive mode adds tax to a net amount. Inclusive mode extracts the tax portion from a gross amount.',
        'benefits' => ['Switch between tax-exclusive and tax-inclusive pricing.', 'Understand the exact tax amount in a transaction.', 'Reuse the same interface for different indirect tax types.'],
        'fields' => [
            'amount' => ['label' => 'Amount', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 250, 'rules' => ['required', 'numeric', 'gt:0']],
            'tax_rate' => ['label' => 'Tax rate (%)', 'type' => 'number', 'step' => '0.01', 'default' => 10, 'rules' => ['required', 'numeric', 'min:0', 'max:100']],
            'tax_mode' => ['label' => 'Pricing mode', 'type' => 'select', 'default' => 'exclusive', 'options' => ['exclusive' => 'Tax exclusive', 'inclusive' => 'Tax inclusive'], 'rules' => ['required', 'in:exclusive,inclusive']],
        ],
        'faqs' => [
            ['question' => 'What is the difference between inclusive and exclusive mode?', 'answer' => 'Exclusive mode adds tax on top of the amount entered. Inclusive mode treats the amount as already including tax and extracts the tax portion.'],
            ['question' => 'Can I use this for any currency?', 'answer' => 'Yes. Tax math is currency-neutral if you keep all amounts in the same currency.'],
        ],
        'related' => ['vat-calculator', 'sales-tax-calculator', 'income-tax-calculator'],
    ],
    'vat-calculator' => [
        'slug' => 'vat-calculator',
        'title' => 'VAT Calculator',
        'h1' => 'VAT Calculator',
        'category' => 'tax-calculators',
        'type' => 'sales_tax',
        'short_description' => 'Add or remove VAT from any amount with flexible tax modes.',
        'meta_title' => 'VAT Calculator: Inclusive and Exclusive Tax Estimate',
        'meta_description' => 'Calculate VAT amount, net amount, and gross total with inclusive or exclusive pricing.',
        'intro' => 'Calculate VAT in either direction using a clean form suitable for many international scenarios.',
        'formula' => 'VAT is calculated by applying the chosen tax rate to the base amount or by extracting it from a tax-inclusive amount.',
        'benefits' => ['Switch between net and gross pricing.', 'Estimate the VAT amount clearly.', 'Compare invoice and receipt totals more confidently.'],
        'fields' => [
            'amount' => ['label' => 'Amount', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 250, 'rules' => ['required', 'numeric', 'gt:0']],
            'tax_rate' => ['label' => 'Tax rate (%)', 'type' => 'number', 'step' => '0.01', 'default' => 20, 'rules' => ['required', 'numeric', 'min:0', 'max:100']],
            'tax_mode' => ['label' => 'Pricing mode', 'type' => 'select', 'default' => 'exclusive', 'options' => ['exclusive' => 'Tax exclusive', 'inclusive' => 'Tax inclusive'], 'rules' => ['required', 'in:exclusive,inclusive']],
        ],
        'faqs' => [
            ['question' => 'Can this be used outside VAT countries?', 'answer' => 'Yes. The math is general enough for any similar tax scenario, though names and rules vary by market.'],
            ['question' => 'Does the calculator round values?', 'answer' => 'Yes. Outputs are rounded to two decimals for readability.'],
        ],
        'related' => ['gst-calculator', 'sales-tax-calculator', 'budget-calculator'],
    ],
    'sales-tax-calculator' => [
        'slug' => 'sales-tax-calculator',
        'title' => 'Sales Tax Calculator',
        'h1' => 'Sales Tax Calculator',
        'category' => 'tax-calculators',
        'type' => 'sales_tax',
        'indexable' => false,
        'short_description' => 'Calculate sales tax for inclusive or exclusive transaction pricing.',
        'meta_title' => 'Sales Tax Calculator: Tax Amount & Total Price',
        'meta_description' => 'Estimate sales tax, pre-tax amount, and final price using tax inclusive or exclusive mode.',
        'intro' => 'Use this calculator for straightforward sales tax estimates across products and services.',
        'formula' => 'Tax is either added to a net amount or extracted from a gross amount depending on the chosen mode.',
        'benefits' => ['Estimate transaction totals quickly.', 'Break out tax from a tax-inclusive price.', 'Reuse the same flexible pattern for multiple jurisdictions.'],
        'fields' => [
            'amount' => ['label' => 'Amount', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 250, 'rules' => ['required', 'numeric', 'gt:0']],
            'tax_rate' => ['label' => 'Tax rate (%)', 'type' => 'number', 'step' => '0.01', 'default' => 8.25, 'rules' => ['required', 'numeric', 'min:0', 'max:100']],
            'tax_mode' => ['label' => 'Pricing mode', 'type' => 'select', 'default' => 'exclusive', 'options' => ['exclusive' => 'Tax exclusive', 'inclusive' => 'Tax inclusive'], 'rules' => ['required', 'in:exclusive,inclusive']],
        ],
        'faqs' => [
            ['question' => 'Can I calculate pre-tax price from a receipt total?', 'answer' => 'Yes. Choose inclusive mode and enter the gross amount plus the applicable tax rate.'],
            ['question' => 'Is the formula different from GST or VAT?', 'answer' => 'The naming differs, but the arithmetic for adding or extracting percentage-based tax is the same here.'],
        ],
        'related' => ['gst-calculator', 'vat-calculator', 'expense-calculator'],
    ],
    'credit-card-interest-calculator' => [
        'slug' => 'credit-card-interest-calculator',
        'title' => 'Credit Card Interest Calculator',
        'h1' => 'Credit Card Interest Calculator',
        'category' => 'credit-calculators',
        'type' => 'credit_card_interest',
        'featured' => true,
        'short_description' => 'Estimate payoff time and total interest for revolving credit card debt.',
        'meta_title' => 'Credit Card Interest Calculator: Payoff Time & Interest',
        'meta_description' => 'Estimate credit card payoff time, total interest, and repayment cost using your balance, APR, and monthly payment.',
        'intro' => 'Project how long revolving debt may take to clear based on your balance, APR, and monthly payment.',
        'formula' => 'Each month interest is added to the outstanding balance and then reduced by the monthly payment until the debt reaches zero.',
        'benefits' => ['See the cost of making only fixed monthly payments.', 'Compare faster payoff scenarios.', 'Estimate interest saved by increasing payments.'],
        'fields' => [
            'balance' => ['label' => 'Outstanding balance', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 6500, 'rules' => ['required', 'numeric', 'gt:0']],
            'rate' => ['label' => 'Annual percentage rate (%)', 'type' => 'number', 'step' => '0.01', 'default' => 19.9, 'rules' => ['required', 'numeric', 'min:0']],
            'monthly_payment' => ['label' => 'Monthly payment', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 250, 'rules' => ['required', 'numeric', 'gt:0']],
        ],
        'faqs' => [
            ['question' => 'What if my payment is too low?', 'answer' => 'If the monthly payment does not exceed the monthly interest, the balance may not reduce. This calculator will flag that case.'],
            ['question' => 'Why is revolving debt expensive?', 'answer' => 'Credit card APRs are often much higher than installment loan rates, so balances can take much longer to clear.'],
        ],
        'related' => ['debt-payoff-calculator', 'loan-calculator', 'budget-calculator'],
    ],
    'debt-payoff-calculator' => [
        'slug' => 'debt-payoff-calculator',
        'title' => 'Debt Payoff Calculator',
        'h1' => 'Debt Payoff Calculator',
        'category' => 'credit-calculators',
        'type' => 'debt_payoff',
        'featured' => true,
        'short_description' => 'Estimate how long it may take to repay debt and the interest you will pay.',
        'meta_title' => 'Debt Payoff Calculator: Time to Clear Debt',
        'meta_description' => 'Estimate debt payoff time, monthly progress, and total interest based on your balance, rate, and payment.',
        'intro' => 'Use this debt payoff calculator to understand how quickly a balance can be cleared under a fixed monthly payment plan.',
        'formula' => 'Debt declines monthly after interest is added and the chosen payment is subtracted until the balance reaches zero.',
        'benefits' => ['Set realistic debt-free timelines.', 'See how higher payments shorten payoff time.', 'Estimate interest cost before choosing a strategy.'],
        'fields' => [
            'balance' => ['label' => 'Debt amount', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 12000, 'rules' => ['required', 'numeric', 'gt:0']],
            'rate' => ['label' => 'Annual interest rate (%)', 'type' => 'number', 'step' => '0.01', 'default' => 12.5, 'rules' => ['required', 'numeric', 'min:0']],
            'monthly_payment' => ['label' => 'Monthly payment', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 450, 'rules' => ['required', 'numeric', 'gt:0']],
        ],
        'faqs' => [
            ['question' => 'What if my payment changes each month?', 'answer' => 'This version assumes a consistent monthly payment for simplicity.'],
            ['question' => 'Does it work for loans and cards?', 'answer' => 'Yes. The debt payoff model works for many interest-bearing balances as long as you use consistent assumptions.'],
        ],
        'related' => ['credit-card-interest-calculator', 'loan-eligibility-calculator', 'budget-calculator'],
    ],
    'loan-eligibility-calculator' => [
        'slug' => 'loan-eligibility-calculator',
        'title' => 'Loan Eligibility Calculator',
        'h1' => 'Loan Eligibility Calculator',
        'category' => 'credit-calculators',
        'type' => 'loan_eligibility',
        'short_description' => 'Estimate a possible loan amount based on income, obligations, rate, and term assumptions.',
        'meta_title' => 'Loan Eligibility Calculator: Estimate Borrowing Capacity',
        'meta_description' => 'Estimate how much you may be able to borrow based on income, obligations, interest rate, and term assumptions.',
        'intro' => 'This calculator estimates borrowing capacity using a simple debt-to-income style model and a fixed-rate repayment assumption.',
        'formula' => 'Available payment capacity = max debt ratio × monthly income - existing monthly obligations. That payment capacity is converted into an estimated eligible loan amount.',
        'benefits' => ['Set realistic borrowing expectations.', 'See how existing obligations affect eligibility.', 'Use a transparent affordability benchmark before applying.'],
        'fields' => [
            'monthly_income' => ['label' => 'Monthly gross income', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 6000, 'rules' => ['required', 'numeric', 'gt:0']],
            'monthly_obligations' => ['label' => 'Existing monthly obligations', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 1200, 'rules' => ['required', 'numeric', 'min:0']],
            'rate' => ['label' => 'Expected annual interest rate (%)', 'type' => 'number', 'step' => '0.01', 'default' => 7.1, 'rules' => ['required', 'numeric', 'min:0']],
            'term_years' => ['label' => 'Loan term (years)', 'type' => 'number', 'step' => '1', 'default' => 20, 'rules' => ['required', 'numeric', 'gt:0']],
        ],
        'faqs' => [
            ['question' => 'Is this lender-approved eligibility?', 'answer' => 'No. It is a planning estimate based on a simple payment-capacity approach, not a lender decision.'],
            ['question' => 'Why use monthly obligations?', 'answer' => 'Existing commitments reduce how much room remains for a new loan payment.'],
        ],
        'related' => ['loan-calculator', 'mortgage-calculator', 'debt-payoff-calculator'],
    ],
    'budget-calculator' => [
        'slug' => 'budget-calculator',
        'title' => 'Budget Calculator',
        'h1' => 'Budget Calculator',
        'category' => 'budget-calculators',
        'type' => 'budget',
        'featured' => true,
        'short_description' => 'See where your money goes with a simple income-versus-expenses budget summary.',
        'meta_title' => 'Budget Calculator: Monthly Budget and Savings Rate',
        'meta_description' => 'Build a monthly budget, total expenses, and savings rate with a clean finance planning calculator.',
        'intro' => 'Create a quick monthly budget snapshot by comparing income against key spending categories.',
        'formula' => 'Total expenses are summed across categories and compared with income to calculate surplus and savings rate.',
        'benefits' => ['See your monthly surplus at a glance.', 'Understand which categories consume the most income.', 'Create a foundation for financial planning.'],
        'fields' => [
            'income' => ['label' => 'Monthly income', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 5000, 'rules' => ['required', 'numeric', 'gt:0']],
            'housing' => ['label' => 'Housing', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 1500, 'rules' => ['required', 'numeric', 'min:0']],
            'food' => ['label' => 'Food', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 600, 'rules' => ['required', 'numeric', 'min:0']],
            'transport' => ['label' => 'Transport', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 350, 'rules' => ['required', 'numeric', 'min:0']],
            'utilities' => ['label' => 'Utilities', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 220, 'rules' => ['required', 'numeric', 'min:0']],
            'healthcare' => ['label' => 'Healthcare', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 180, 'rules' => ['required', 'numeric', 'min:0']],
            'other' => ['label' => 'Other spending', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 700, 'rules' => ['required', 'numeric', 'min:0']],
        ],
        'faqs' => [
            ['question' => 'Why keep the categories simple?', 'answer' => 'A simpler structure makes it easier to spot the largest spending pressures and build a quick monthly picture without extra setup.'],
            ['question' => 'What is savings rate?', 'answer' => 'Savings rate is the percentage of monthly income left after expenses.'],
        ],
        'related' => ['expense-calculator', 'take-home-salary-calculator', 'currency-converter'],
    ],
    'expense-calculator' => [
        'slug' => 'expense-calculator',
        'title' => 'Expense Calculator',
        'h1' => 'Expense Calculator',
        'category' => 'budget-calculators',
        'type' => 'expense',
        'indexable' => false,
        'short_description' => 'Add up monthly expenses and identify your largest spending category.',
        'meta_title' => 'Expense Calculator: Total Spending by Category',
        'meta_description' => 'Calculate total monthly expenses and identify the largest spending category with a simple expense calculator.',
        'intro' => 'Track key monthly expense categories and see where the biggest share of your spending goes.',
        'formula' => 'Total expenses equal the sum of all entered categories. The largest category is identified by comparing all values.',
        'benefits' => ['Quickly total household or personal spending.', 'Spot oversized cost categories.', 'Create cleaner inputs for a more structured budgeting workflow.'],
        'fields' => [
            'housing' => ['label' => 'Housing', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 1500, 'rules' => ['required', 'numeric', 'min:0']],
            'food' => ['label' => 'Food', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 600, 'rules' => ['required', 'numeric', 'min:0']],
            'transport' => ['label' => 'Transport', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 350, 'rules' => ['required', 'numeric', 'min:0']],
            'utilities' => ['label' => 'Utilities', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 220, 'rules' => ['required', 'numeric', 'min:0']],
            'healthcare' => ['label' => 'Healthcare', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 180, 'rules' => ['required', 'numeric', 'min:0']],
            'other' => ['label' => 'Other spending', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 700, 'rules' => ['required', 'numeric', 'min:0']],
        ],
        'faqs' => [
            ['question' => 'What counts as other spending?', 'answer' => 'Anything not covered by the listed categories, such as subscriptions, entertainment, or miscellaneous purchases.'],
            ['question' => 'How is this different from a full expense tracker?', 'answer' => 'This page is meant for quick category totals and spending comparisons, not for storing transactions over time.'],
        ],
        'related' => ['budget-calculator', 'salary-calculator', 'sales-tax-calculator'],
    ],
    'currency-converter' => [
        'slug' => 'currency-converter',
        'title' => 'Currency Converter',
        'h1' => 'Currency Converter',
        'category' => 'budget-calculators',
        'type' => 'currency_converter',
        'indexable' => false,
        'short_description' => 'Convert between currencies using a manual exchange rate input for travel, planning, and invoice scenarios.',
        'meta_title' => 'Currency Converter: Manual Exchange Rate Converter',
        'meta_description' => 'Convert currency values using a manual exchange rate input with a clean, flexible currency converter interface.',
        'intro' => 'Use this currency converter to estimate values between major currencies with your chosen exchange rate for travel, pricing, remittance, and planning scenarios.',
        'formula' => 'Converted amount = source amount × exchange rate.',
        'benefits' => ['Estimate conversions quickly with your chosen rate.', 'Test travel, invoice, and budgeting scenarios with custom inputs.', 'Keep a flexible currency workflow available for worldwide users.'],
        'fields' => [
            'amount' => ['label' => 'Amount', 'type' => 'number', 'step' => '0.01', 'prefix' => '$', 'default' => 100, 'rules' => ['required', 'numeric', 'gt:0']],
            'from_currency' => ['label' => 'From currency', 'type' => 'select', 'default' => 'USD', 'options' => ['USD' => 'USD', 'EUR' => 'EUR', 'GBP' => 'GBP', 'JPY' => 'JPY', 'AUD' => 'AUD'], 'rules' => ['required', 'in:USD,EUR,GBP,JPY,AUD']],
            'to_currency' => ['label' => 'To currency', 'type' => 'select', 'default' => 'EUR', 'options' => ['USD' => 'USD', 'EUR' => 'EUR', 'GBP' => 'GBP', 'JPY' => 'JPY', 'AUD' => 'AUD'], 'rules' => ['required', 'in:USD,EUR,GBP,JPY,AUD']],
            'exchange_rate' => ['label' => 'Exchange rate', 'type' => 'number', 'step' => '0.0001', 'default' => 0.92, 'rules' => ['required', 'numeric', 'gt:0']],
        ],
        'faqs' => [
            ['question' => 'Are live exchange rates included?', 'answer' => 'This version uses a manual exchange rate, so you can enter the rate you want to use for planning or comparison purposes.'],
            ['question' => 'Can I still use it now?', 'answer' => 'Yes. Enter a custom exchange rate to convert any amount manually.'],
        ],
        'related' => ['budget-calculator', 'expense-calculator', 'sales-tax-calculator'],
    ],
];
