<?php

return [
    'default' => 'us',
    'supported' => [
        'in' => [
            'code' => 'in',
            'name' => 'India',
            'flag' => 'IN',
            'currency' => 'INR',
            'symbol' => '₹',
            'locale' => 'en_IN',
            'language' => 'en',
            'tax_model' => 'in',
        ],
        'us' => [
            'code' => 'us',
            'name' => 'United States',
            'flag' => 'US',
            'currency' => 'USD',
            'symbol' => '$',
            'locale' => 'en_US',
            'language' => 'en',
            'tax_model' => 'us',
        ],
        'gb' => [
            'code' => 'gb',
            'name' => 'United Kingdom',
            'flag' => 'GB',
            'currency' => 'GBP',
            'symbol' => '£',
            'locale' => 'en_GB',
            'language' => 'en',
            'tax_model' => 'uk',
        ],
        'ca' => [
            'code' => 'ca',
            'name' => 'Canada',
            'flag' => 'CA',
            'currency' => 'CAD',
            'symbol' => 'CA$',
            'locale' => 'en_CA',
            'language' => 'en',
            'tax_model' => 'generic',
        ],
        'au' => [
            'code' => 'au',
            'name' => 'Australia',
            'flag' => 'AU',
            'currency' => 'AUD',
            'symbol' => 'A$',
            'locale' => 'en_AU',
            'language' => 'en',
            'tax_model' => 'generic',
        ],
        'sg' => [
            'code' => 'sg',
            'name' => 'Singapore',
            'flag' => 'SG',
            'currency' => 'SGD',
            'symbol' => 'S$',
            'locale' => 'en_SG',
            'language' => 'en',
            'tax_model' => 'generic',
        ],
        'ae' => [
            'code' => 'ae',
            'name' => 'United Arab Emirates',
            'flag' => 'AE',
            'currency' => 'AED',
            'symbol' => 'AED',
            'locale' => 'en_AE',
            'language' => 'en',
            'tax_model' => 'generic',
        ],
        'sa' => [
            'code' => 'sa',
            'name' => 'Saudi Arabia',
            'flag' => 'SA',
            'currency' => 'SAR',
            'symbol' => 'SAR',
            'locale' => 'en_SA',
            'language' => 'en',
            'tax_model' => 'generic',
        ],
        'my' => [
            'code' => 'my',
            'name' => 'Malaysia',
            'flag' => 'MY',
            'currency' => 'MYR',
            'symbol' => 'RM',
            'locale' => 'en_MY',
            'language' => 'en',
            'tax_model' => 'generic',
        ],
        'jp' => [
            'code' => 'jp',
            'name' => 'Japan',
            'flag' => 'JP',
            'currency' => 'JPY',
            'symbol' => '¥',
            'locale' => 'ja_JP',
            'language' => 'ja',
            'tax_model' => 'generic',
        ],
        'de' => [
            'code' => 'de',
            'name' => 'Germany',
            'flag' => 'DE',
            'currency' => 'EUR',
            'symbol' => '€',
            'locale' => 'de_DE',
            'language' => 'de',
            'tax_model' => 'generic',
        ],
        'fr' => [
            'code' => 'fr',
            'name' => 'France',
            'flag' => 'FR',
            'currency' => 'EUR',
            'symbol' => '€',
            'locale' => 'fr_FR',
            'language' => 'fr',
            'tax_model' => 'generic',
        ],
        'es' => [
            'code' => 'es',
            'name' => 'Spain',
            'flag' => 'ES',
            'currency' => 'EUR',
            'symbol' => '€',
            'locale' => 'es_ES',
            'language' => 'es',
            'tax_model' => 'generic',
        ],
        'it' => [
            'code' => 'it',
            'name' => 'Italy',
            'flag' => 'IT',
            'currency' => 'EUR',
            'symbol' => '€',
            'locale' => 'it_IT',
            'language' => 'it',
            'tax_model' => 'generic',
        ],
        'nl' => [
            'code' => 'nl',
            'name' => 'Netherlands',
            'flag' => 'NL',
            'currency' => 'EUR',
            'symbol' => '€',
            'locale' => 'nl_NL',
            'language' => 'nl',
            'tax_model' => 'generic',
        ],
        'br' => [
            'code' => 'br',
            'name' => 'Brazil',
            'flag' => 'BR',
            'currency' => 'BRL',
            'symbol' => 'R$',
            'locale' => 'pt_BR',
            'language' => 'pt',
            'tax_model' => 'generic',
        ],
        'mx' => [
            'code' => 'mx',
            'name' => 'Mexico',
            'flag' => 'MX',
            'currency' => 'MXN',
            'symbol' => 'MX$',
            'locale' => 'es_MX',
            'language' => 'es',
            'tax_model' => 'generic',
        ],
        'za' => [
            'code' => 'za',
            'name' => 'South Africa',
            'flag' => 'ZA',
            'currency' => 'ZAR',
            'symbol' => 'R',
            'locale' => 'en_ZA',
            'language' => 'en',
            'tax_model' => 'generic',
        ],
        'nz' => [
            'code' => 'nz',
            'name' => 'New Zealand',
            'flag' => 'NZ',
            'currency' => 'NZD',
            'symbol' => 'NZ$',
            'locale' => 'en_NZ',
            'language' => 'en',
            'tax_model' => 'generic',
        ],
        'ch' => [
            'code' => 'ch',
            'name' => 'Switzerland',
            'flag' => 'CH',
            'currency' => 'CHF',
            'symbol' => 'CHF',
            'locale' => 'de_CH',
            'language' => 'de',
            'tax_model' => 'generic',
        ],
        'se' => [
            'code' => 'se',
            'name' => 'Sweden',
            'flag' => 'SE',
            'currency' => 'SEK',
            'symbol' => 'kr',
            'locale' => 'sv_SE',
            'language' => 'sv',
            'tax_model' => 'generic',
        ],
        'no' => [
            'code' => 'no',
            'name' => 'Norway',
            'flag' => 'NO',
            'currency' => 'NOK',
            'symbol' => 'kr',
            'locale' => 'nb_NO',
            'language' => 'no',
            'tax_model' => 'generic',
        ],
        'dk' => [
            'code' => 'dk',
            'name' => 'Denmark',
            'flag' => 'DK',
            'currency' => 'DKK',
            'symbol' => 'kr',
            'locale' => 'da_DK',
            'language' => 'da',
            'tax_model' => 'generic',
        ],
        'id' => [
            'code' => 'id',
            'name' => 'Indonesia',
            'flag' => 'ID',
            'currency' => 'IDR',
            'symbol' => 'Rp',
            'locale' => 'id_ID',
            'language' => 'id',
            'tax_model' => 'generic',
        ],
        'ph' => [
            'code' => 'ph',
            'name' => 'Philippines',
            'flag' => 'PH',
            'currency' => 'PHP',
            'symbol' => '₱',
            'locale' => 'en_PH',
            'language' => 'en',
            'tax_model' => 'generic',
        ],
        'eu' => [
            'code' => 'eu',
            'name' => 'Europe',
            'flag' => 'EU',
            'currency' => 'EUR',
            'symbol' => '€',
            'locale' => 'en_IE',
            'language' => 'en',
            'tax_model' => 'generic',
        ],
    ],
    'region_map' => [
        'IN' => 'in',
        'US' => 'us',
        'GB' => 'gb',
        'CA' => 'ca',
        'AU' => 'au',
        'SG' => 'sg',
        'AE' => 'ae',
        'SA' => 'sa',
        'MY' => 'my',
        'JP' => 'jp',
        'DE' => 'eu',
        'FR' => 'eu',
        'IT' => 'eu',
        'ES' => 'eu',
        'NL' => 'eu',
        'BE' => 'eu',
        'IE' => 'eu',
        'PT' => 'eu',
        'AT' => 'eu',
        'FI' => 'eu',
        'SE' => 'eu',
        'DK' => 'eu',
        'PL' => 'eu',
        'CZ' => 'eu',
        'RO' => 'eu',
        'GR' => 'eu',
        'HU' => 'eu',
        'BR' => 'br',
        'MX' => 'mx',
        'ZA' => 'za',
        'NZ' => 'nz',
        'CH' => 'ch',
        'SE' => 'se',
        'NO' => 'no',
        'DK' => 'dk',
        'ID' => 'id',
        'PH' => 'ph',
    ],
];
